"""Contract tests for the WS10 (thrust-subconditions) engine, committed at the freeze BEFORE the
engine exists. They define what ``scripts/ws10_subconditions.py`` and ``scripts/ws10_run.py`` must
do; the Opus build makes them pass without changing them. Every value comes from
``spec/ws10_prereg_spec.json`` (the engine reads it and never restates it) and from the planted
fixture ``tests/fixtures/ws10/expected.json`` regenerated by ``tests/make_ws10_fixture.py``.

Required API (frozen). scripts/ws10_subconditions.py:
  SPEC_PATH                                   Path of spec/ws10_prereg_spec.json
  load_spec() -> dict                         the spec; a missing key is a FreezeViolation when read with get(spec, "a.b.c")
  get(spec, dotted) -> value                  raises FreezeViolation on a missing key (never a default)
  spec_hash() -> str                          sha256 hex of the spec file bytes
  FreezeViolation, BurnInRefusal, NonSessionDate, ComparatorMisuse   exception classes
  resolve_session(date, sessions) -> Timestamp               raises NonSessionDate if `date` is not in `sessions`
  candidate_share(close, member) -> Series                   per cent, 100 * count / members (multiplication first),
        NaN where fewer than shared.share_nan_below_members members carry the required history; name == member
  daily_fire(share, threshold) -> Series[bool]               share >= threshold, NaN -> False
  fresh_events(share, threshold, comp) -> DatetimeIndex      first session at or above after shared.below_sessions
        consecutive DEFINED sessions strictly below; admitted on data_ok sessions at or after the first data_ok
        session; raises BurnInRefusal when comp has no data_ok session
  candidate_events(close, member, comp) -> DatetimeIndex     candidate_share then fresh_events; raises BurnInRefusal
        when len(close) < HL_LOOKBACK + the member's window_sessions (the burn-in plus its own 20 or 10)
  member_fresh_fires(boolean, comp) -> DatetimeIndex         existing_member_fresh_fire.rule on data_ok sessions
  cofire_share(cand_events, fire_dates, sessions) -> float   per cent of cand_events within redundancy.window_sessions
        (either direction) of a fire date; NaN for an empty candidate set
  redundancy(cand_events, fires_by_dim, own_dimension, sessions) -> dict  keys own, d1, d4 (per cent) and status in
        {DISTINCT, REDUNDANT, MISPLACED, NO_EVENTS} per redundancy.status_rule; fires_by_dim maps d1..d4 -> DatetimeIndex
  composite_with_members(panels, extra, config=None) -> DataFrame   compute_composite with extra {dim: Series[bool]}
        OR-ed into dim; equal to compute_composite(panels) on every engine column when every extra is False
  fresh_at(comp, threshold) -> DatetimeIndex                 event and n_dimensions >= threshold and data_ok
  before_set(comp, threshold) -> DatetimeIndex               the SEEN four-dimension set: takes no candidate argument
  added_events(before, after, threshold) -> DatetimeIndex    fresh_at(after) dates absent from fresh_at(before)
  class CandidateRegistry: register(name, events); assert_comparator(events) raises ComparatorMisuse when `events`
        equals any registered candidate or added set (the seen four-dimension set is the only admissible comparator
        besides the null)
  forward_stats(events, index_series, horizon_sessions) -> {"n", "win_rate", "median"}  lagged one session through
        forward_returns.conditional_table (signal close T, window from the close of T+1)
  forward_window_end(sessions, start, horizon_sessions) -> Timestamp    sessions[get_loc(start) + h]; NonSessionDate
  cluster_ids(dates, gap_days) -> list[int]; cluster_count(dates, gap_days) -> int   a gap > gap_days splits
  null_sets(events, valid_sessions, horizon_sessions, draws, seed_key) -> list[DatetimeIndex]
        count-matched, cluster-structured (clusters.gap_calendar_days): same cluster count, cluster sizes and
        within-cluster session offsets; cluster start sessions uniform without replacement over valid_sessions on
        which the whole cluster fits and every event sits at least horizon_sessions before the end of valid_sessions;
        clusters separated by more than gap_days calendar days; numpy.random.default_rng(seed_key)
  null_draws(events, valid_sessions, index_series, horizon_sessions, draws, seed_key) -> ndarray (draws, 2)
        columns win_rate, median of each drawn set's lagged forward returns
  mc_p(observed, draw_values) -> float                       (1 + count at or beyond) / (1 + draws)
  per_horizon_p(p_win, p_med) -> float                       max
  holm(pvals, alpha) -> {"reject": {name: bool}, "steps": [{"name", "p", "threshold", "reject"}]}
  power(events, valid_sessions, index_series, horizon_sessions, delta_pp, null_values, draws, seed_key, alpha,
        family_size) -> float   share of drawn sets whose max(p_win, p_med) at +delta_pp per horizon is <= alpha / family_size
  cell_status(cleared, power_keyed) -> "PASS" | "FAIL" | "UNRESOLVED"        power.cell_status_rule
  clause_status(early, late) -> "PASS" | "FAIL" | "UNRESOLVED"              power.clause_status_rule
  verdict(g1, g2, g3, stopped=False, thin=False) -> str     verdict.rule_in_order; g1 {cand: status}, g2 {cand: status}
scripts/ws10_run.py:
  Stop                                                      the FAIL_STOP exception
  spec_hash_or_stop(frozen) -> str                          Stop when the spec hash differs from `frozen`
  check_engine_modules(spec) -> dict                        Stop when any pinned module hash differs
  check_frozen_tree_clean(status_lines) -> None             Stop when PREREG_thrust-subconditions.md, spec/ or tests/
        appear modified, added, renamed or untracked in `git status --porcelain` lines
  event_set_guard(observed, expected) -> None               Stop when any key of `expected` differs in `observed`

Python months are 1-indexed. Date arithmetic goes through pandas only.
"""

from __future__ import annotations

import hashlib
import inspect
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

TESTS = Path(__file__).resolve().parent
ROOT = TESTS.parent
FIX = TESTS / "fixtures" / "ws10"
sys.path.insert(0, str(TESTS))
sys.path.insert(0, str(ROOT / "scripts"))

import make_ws10_fixture as ref  # noqa: E402
import compute_breadth as cb  # noqa: E402

FROZEN_SPEC_SHA256 = "fb5b61ac9d0b3fb5c907b188a5fc3a293658d3ae0ac5e722df091c901a97aafb"

ws10 = pytest.importorskip("ws10_subconditions", reason="engine not built yet: scripts/ws10_subconditions.py missing")
runner = pytest.importorskip("ws10_run", reason="engine not built yet: scripts/ws10_run.py missing")


def _dates(xs) -> list[str]:
    return [str(pd.Timestamp(x).date()) for x in xs]


@pytest.fixture(scope="module")
def sp():
    return ws10.load_spec()


@pytest.fixture(scope="module")
def fx():
    close, volume = ref.planted()
    expected = json.loads((FIX / "expected.json").read_text(encoding="utf-8"))
    panels = cb.build_panels(close, volume)
    before = cb.compute_composite(panels)
    return close, volume, panels, before, expected


# ---------------------------------------------------------------- spec and hashes

def test_spec_hash_matches_frozen_value():
    assert hashlib.sha256((ROOT / "spec" / "ws10_prereg_spec.json").read_bytes()).hexdigest() == FROZEN_SPEC_SHA256
    assert ws10.spec_hash() == FROZEN_SPEC_SHA256
    assert runner.spec_hash_or_stop(FROZEN_SPEC_SHA256) == FROZEN_SPEC_SHA256
    with pytest.raises(runner.Stop):
        runner.spec_hash_or_stop("0" * 64)


def test_missing_spec_key_raises_rather_than_defaulting(sp):
    assert ws10.get(sp, "candidates.S-D3.threshold_pct") == 55.0
    assert ws10.get(sp, "candidates.S-D2.threshold_pct") == 90.0
    with pytest.raises(ws10.FreezeViolation):
        ws10.get(sp, "candidates.S-D3.threshold_pct_tuned")


def test_engine_module_hashes_are_pinned(sp):
    got = runner.check_engine_modules(sp)
    assert got == sp["engine"]["modules_sha256"]
    tampered = json.loads(json.dumps(sp))
    tampered["engine"]["modules_sha256"]["compute_breadth.py"] = "0" * 64
    with pytest.raises(runner.Stop):
        runner.check_engine_modules(tampered)


def test_dirty_frozen_tree_makes_the_runner_refuse():
    runner.check_frozen_tree_clean([" M scripts/ws10_subconditions.py", "?? data_local/x.json", " M README.md"])
    for line in (" M PREREG_thrust-subconditions.md", "?? spec/ws10_prereg_spec.json", "A  tests/test_ws10_contract.py",
                 " M tests/fixtures/ws10/expected.json", 'R  old.md -> "PREREG_thrust-subconditions.md"'):
        with pytest.raises(runner.Stop):
            runner.check_frozen_tree_clean([line])


def test_event_set_guard_stops_on_a_mismatch(sp):
    expected = sp["data"]["expected_panel"]["event_set_guard"]
    observed = {k: v for k, v in expected.items() if k not in ("source", "on_miss")}
    runner.event_set_guard(observed, expected)
    wrong = dict(observed)
    wrong["fresh_events_ge1_on_or_before_2026-09-01"] = 97
    with pytest.raises(runner.Stop):
        runner.event_set_guard(wrong, expected)
    with pytest.raises(runner.Stop):
        runner.event_set_guard({}, expected)


# ---------------------------------------------------------------- candidate shares and events on the planted panel

def test_candidate_shares_match_the_fixture(fx, sp):
    close, volume, panels, before, expected = fx
    for member in ("S-D3", "S-D2"):
        share = ws10.candidate_share(close, member)
        assert share.name == member
        assert str(share.first_valid_index().date()) == expected["first_defined"][member]
        for d, want in expected["shares"][member].items():
            got = share.loc[pd.Timestamp(d)]
            if want is None:
                assert pd.isna(got)
            elif want in (55.0, 90.0):
                assert got == want, f"{member} at {d}: expected exactly {want}, got {got!r}"
            else:
                assert abs(got - want) < 1e-9, f"{member} at {d}: {got} vs {want}"


def test_fresh_events_match_the_fixture(fx, sp):
    close, volume, panels, before, expected = fx
    for member in ("S-D3", "S-D2"):
        share = ws10.candidate_share(close, member)
        thr = ws10.get(sp, f"candidates.{member}.threshold_pct")
        assert _dates(ws10.fresh_events(share, thr, before)) == expected["fresh_events"][member]
        assert _dates(ws10.candidate_events(close, member, before)) == expected["fresh_events"][member]
        assert int(ws10.daily_fire(share, thr).sum()) == expected["daily_fire_counts"][member]


def test_share_nan_below_the_member_floor(sp):
    close, volume = ref.planted()
    thin = close.iloc[:, :300]
    assert ws10.candidate_share(thin, "S-D2").isna().all(), "fewer than 400 members with history must give NaN"


# ---------------------------------------------------------------- refusal paths

def test_refuses_any_computation_before_the_burn_in_plus_its_own_window(sp):
    close, volume = ref.planted()
    burn = int(ws10.get(sp, "engine.constants.HL_LOOKBACK"))
    short = close.iloc[: burn + 15]                       # 267 sessions: 252 + 10 fits S-D2, 252 + 20 does not fit S-D3
    comp_short = cb.compute_composite(cb.build_panels(short, volume.iloc[: burn + 15]))
    assert comp_short["data_ok"].any()
    ws10.candidate_events(short, "S-D2", comp_short)
    with pytest.raises(ws10.BurnInRefusal):
        ws10.candidate_events(short, "S-D3", comp_short)
    tiny = close.iloc[:100]
    comp_tiny = cb.compute_composite(cb.build_panels(tiny, volume.iloc[:100]))
    assert not comp_tiny["data_ok"].any()
    for member in ("S-D3", "S-D2"):
        with pytest.raises(ws10.BurnInRefusal):
            ws10.candidate_events(tiny, member, comp_tiny)
        with pytest.raises(ws10.BurnInRefusal):
            ws10.fresh_events(ws10.candidate_share(tiny, member), 55.0, comp_tiny)


def test_no_event_inside_the_burn_in_even_when_the_share_crosses(fx, sp):
    close, volume, panels, before, expected = fx
    share = ws10.candidate_share(close, "S-D3")
    first_ok = pd.Timestamp(expected["first_data_ok_session"])
    assert share.loc[pd.Timestamp("2019-04-10")] == 60.0 and pd.Timestamp("2019-04-10") < first_ok
    ev = ws10.fresh_events(share, 55.0, before)
    assert len(ev) and ev.min() >= first_ok


def test_non_session_date_is_refused(fx):
    close, volume, panels, before, expected = fx
    cal = close.index
    assert ws10.resolve_session(pd.Timestamp("2020-04-07"), cal) == pd.Timestamp("2020-04-07")
    for bad in ("2020-06-13", "2020-06-14", "2030-01-02"):             # a Saturday, a Sunday, beyond the panel
        with pytest.raises(ws10.NonSessionDate):
            ws10.resolve_session(pd.Timestamp(bad), cal)
        with pytest.raises(ws10.NonSessionDate):
            ws10.forward_window_end(cal, pd.Timestamp(bad), 21)


# ---------------------------------------------------------------- the member conditions pinned on tiny series

def test_flat_series_is_at_its_closing_high_under_the_inclusive_rule(sp):
    cal = pd.bdate_range("2021-01-04", periods=40)
    flat = pd.DataFrame({f"N{i:03d}": 100.0 for i in range(400)}, index=cal)
    share = ws10.candidate_share(flat, "S-D3")
    assert share.iloc[19:].eq(100.0).all(), "close >= max over the window including today holds on a flat series"
    assert share.iloc[:19].isna().all(), "no share before 20 sessions of history"
    assert ws10.candidate_share(flat, "S-D2").iloc[9:].eq(0.0).all(), "strictly above its own flat average is never true"


def test_step_then_flat_sits_above_its_ten_session_average_for_exactly_nine_sessions(sp):
    cal = pd.bdate_range("2021-01-04", periods=40)
    path = np.full(40, 100.0)
    path[20:] = 110.0                                  # one step on session 20, then exactly flat
    frame = pd.DataFrame({f"N{i:03d}": path for i in range(400)}, index=cal)
    share = ws10.candidate_share(frame, "S-D2")
    assert share.iloc[20:29].eq(100.0).all()           # sessions 20..28: above (j = 0..8)
    assert share.iloc[29] == 0.0                       # j = 9: the window is all 110, a tie is not "above"
    d3 = ws10.candidate_share(frame, "S-D3")
    assert d3.iloc[20:].eq(100.0).all()                # a step then flat stays at its 20-session high


def test_exactly_twenty_defined_sessions_below_are_required(fx, sp):
    close, volume, panels, before, expected = fx
    cal = close.index[-60:]
    comp = before.loc[cal].copy()
    assert comp["data_ok"].all()
    twenty = pd.Series([60.0] * 5 + [50.0] * 20 + [60.0] + [50.0] * 34, index=cal)
    nineteen = pd.Series([60.0] * 5 + [50.0] * 19 + [60.0] + [50.0] * 35, index=cal)
    broken = twenty.copy()
    broken.iloc[10] = np.nan
    assert _dates(ws10.fresh_events(twenty, 55.0, comp)) == [str(cal[25].date())]
    assert _dates(ws10.fresh_events(nineteen, 55.0, comp)) == []
    assert _dates(ws10.fresh_events(broken, 55.0, comp)) == []


# ---------------------------------------------------------------- redundancy

def test_member_fresh_fires_match_the_fixture(fx, sp):
    close, volume, panels, before, expected = fx
    for dim, names in sp["engine"]["members"].items():
        for m in names:
            assert _dates(ws10.member_fresh_fires(before[m], before)) == expected["member_fresh_fires"][m], m


def test_redundancy_on_the_planted_panel(fx, sp):
    close, volume, panels, before, expected = fx
    fires_by_dim = {}
    for dim, names in sp["engine"]["members"].items():
        fires_by_dim[dim] = pd.DatetimeIndex(sorted({d for m in names for d in ws10.member_fresh_fires(before[m], before)}))
    for member in ("S-D3", "S-D2"):
        cand = ws10.candidate_events(close, member, before)
        got = ws10.redundancy(cand, fires_by_dim, ws10.get(sp, f"candidates.{member}.dimension"), close.index)
        want = expected["redundancy"][member]
        for k in ("own", "d1", "d4"):
            assert abs(got[k] - want[k]) < 1e-9, (member, k, got[k], want[k])
        assert got["status"] in ("DISTINCT", "REDUNDANT", "MISPLACED")


def test_redundancy_rule_known_cases(sp):
    cal = pd.bdate_range("2020-01-02", periods=200)
    cand = pd.DatetimeIndex([cal[50], cal[53], cal[55], cal[106], cal[180]])      # offsets 0, 3, 5, 6, 30 from fires
    own = pd.DatetimeIndex([cal[50], cal[100], cal[150]])
    assert ws10.cofire_share(cand, own, cal) == 60.0
    assert pd.isna(ws10.cofire_share(pd.DatetimeIndex([]), own, cal))
    none = pd.DatetimeIndex([])
    r = ws10.redundancy(cand, {"d1": none, "d2": none, "d3": own, "d4": none}, "d3", cal)
    assert r["own"] == 60.0 and r["d1"] == 0.0 and r["d4"] == 0.0 and r["status"] == "DISTINCT"
    heavy = pd.DatetimeIndex([cal[50], cal[53], cal[55], cal[106]])                 # 4 of 5 within the window
    r = ws10.redundancy(cand, {"d1": none, "d2": none, "d3": heavy, "d4": none}, "d3", cal)
    assert r["own"] == 80.0 and r["status"] == "REDUNDANT"
    seventy = pd.DatetimeIndex([cal[i] for i in (50, 53, 55, 106, 180)])
    cand10 = pd.DatetimeIndex([cal[i] for i in (50, 53, 55, 106, 180, 10, 20, 30, 120, 190)])
    r = ws10.redundancy(cand10, {"d1": none, "d2": none, "d3": seventy[:4], "d4": none}, "d3", cal)
    assert r["own"] == 40.0
    r = ws10.redundancy(cand, {"d1": none, "d2": none, "d3": pd.DatetimeIndex([cal[50], cal[53], cal[55]]), "d4": own}, "d3", cal)
    assert r["own"] == 60.0 and r["d4"] == 60.0 and r["status"] == "DISTINCT", "equal shares are not MISPLACED"
    r = ws10.redundancy(cand, {"d1": none, "d2": none, "d3": pd.DatetimeIndex([cal[50]]), "d4": own}, "d3", cal)
    assert r["own"] == 20.0 and r["d4"] == 60.0 and r["status"] == "MISPLACED"
    exact70 = ws10.redundancy(pd.DatetimeIndex([cal[i] for i in (50, 51, 52, 53, 54, 55, 56, 120, 150, 190)]),
                              {"d1": none, "d2": none, "d3": pd.DatetimeIndex([cal[52]]), "d4": none}, "d3", cal)
    assert exact70["own"] == 70.0 and exact70["status"] == "DISTINCT", "exactly 70 is not above 70"
    assert ws10.redundancy(pd.DatetimeIndex([]), {"d1": none, "d2": none, "d3": own, "d4": none}, "d3", cal)["status"] == "NO_EVENTS"


# ---------------------------------------------------------------- H-M: the composite with members

def test_composite_with_members_is_the_engine_when_nothing_is_admitted(fx):
    close, volume, panels, before, expected = fx
    off = pd.Series(False, index=close.index, name="off")
    same = ws10.composite_with_members(panels, {"d2": off, "d3": off})
    pd.testing.assert_frame_equal(same[before.columns], before)
    assert _dates(ws10.before_set(before, 2)) == expected["h_m"]["ge2"]["before"]
    assert _dates(ws10.fresh_at(before, 3)) == expected["h_m"]["ge3"]["before"]


def test_added_events_match_the_fixture(fx, sp):
    close, volume, panels, before, expected = fx
    extras = {}
    for member in ("S-D3", "S-D2"):
        fire = ws10.daily_fire(ws10.candidate_share(close, member), ws10.get(sp, f"candidates.{member}.threshold_pct"))
        fire.name = member
        extras[ws10.get(sp, f"candidates.{member}.dimension")] = fire
    after = ws10.composite_with_members(panels, extras)
    for thr in (2, 3):
        want = expected["h_m"][f"ge{thr}"]
        assert _dates(ws10.fresh_at(after, thr)) == want["after"]
        assert _dates(ws10.added_events(before, after, thr)) == want["added"]
    # the OR itself: a dimension REPLACED by its candidate would leave n_dimensions untouched behind the memory
    assert {d: int(after[d].sum()) for d in ("d1", "d2", "d3", "d4")} == expected["h_m"]["after_dim_true_counts"]
    assert set(after["d3_on"][after["d3_member_S-D3"]]) == {True}, "an admitted member switches its dimension on"


def test_the_seen_set_is_the_only_admissible_comparator(fx):
    close, volume, panels, before, expected = fx
    assert "candidate" not in " ".join(inspect.signature(ws10.before_set).parameters)
    reg = ws10.CandidateRegistry()
    cand = ws10.candidate_events(close, "S-D3", before)
    added = pd.DatetimeIndex(pd.to_datetime(expected["h_m"]["ge2"]["added"]))
    reg.register("S-D3", cand)
    reg.register("H-M.ge2.added", added)
    reg.assert_comparator(ws10.before_set(before, 2))                   # the seen four-dimension set is admissible
    for bad in (cand, added, pd.DatetimeIndex(sorted(cand))):
        with pytest.raises(ws10.ComparatorMisuse):
            reg.assert_comparator(bad)


# ---------------------------------------------------------------- forward returns, lag, windows, clusters

def test_forward_stats_are_lagged_one_session(sp):
    cal = pd.bdate_range("2019-01-02", periods=60)
    spx = pd.Series(100.0 + np.arange(60), index=cal)
    k, h = 30, int(ws10.get(sp, "horizons.sessions.1m"))
    honest = spx.iloc[k + 1 + h] / spx.iloc[k + 1] - 1.0
    leaked = spx.iloc[k + h] / spx.iloc[k] - 1.0
    got = ws10.forward_stats(pd.DatetimeIndex([cal[k]]), spx, h)
    assert got["n"] == 1 and abs(got["median"] - honest) < 1e-12 and abs(got["median"] - leaked) > 1e-9
    assert ws10.forward_stats(pd.DatetimeIndex([cal[50]]), spx, h)["n"] == 0, "an incomplete window is dropped"


def test_forward_window_boundaries_on_the_fixture_calendar(fx, sp):
    close, volume, panels, before, expected = fx
    h = int(ws10.get(sp, "horizons.sessions.1m"))
    for start, want in expected["boundaries_1m"].items():          # a year boundary and a month boundary
        assert str(ws10.forward_window_end(close.index, pd.Timestamp(start), h).date()) == want


def test_cluster_rule_known_cases(fx, sp):
    close, volume, panels, before, expected = fx
    gap = int(ws10.get(sp, "clusters.gap_calendar_days"))
    kc = expected["cluster_known_case"]
    assert ws10.cluster_ids(pd.to_datetime(kc["dates"]), gap) == [0, 0, 1]
    assert ws10.cluster_ids(pd.to_datetime(kc["dates_b"]), gap) == [0, 0, 0]
    assert ws10.cluster_count(pd.to_datetime(kc["dates"]), gap) == 2
    assert ws10.cluster_count(pd.DatetimeIndex([]), gap) == 0


# ---------------------------------------------------------------- the null

def _null_setting():
    cal = pd.bdate_range("2019-01-02", periods=600)
    rng = np.random.default_rng(3)
    spx = pd.Series(100.0 * np.cumprod(1.0 + rng.normal(0.0003, 0.01, 600)), index=cal)
    events = pd.DatetimeIndex([cal[300], cal[306], cal[314], cal[450]])   # one cluster of three, one singleton
    return cal, spx, events


def test_null_sets_are_count_matched_and_cluster_structured(sp):
    cal, spx, events = _null_setting()
    gap = int(ws10.get(sp, "clusters.gap_calendar_days"))
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    valid = cal[251:]
    sets = ws10.null_sets(events, valid, h, 60, [19901228, 0])
    assert len(sets) == 60
    pos = {d: i for i, d in enumerate(cal)}
    for s in sets:
        assert len(s) == len(events) and list(s) == sorted(s)
        assert all(d in valid for d in s), "every drawn event is a session of the valid window"
        assert max(pos[d] for d in s) + h <= len(cal) - 1, "every forward window is complete"
        ids = ws10.cluster_ids(s, gap)
        assert ids == [0, 0, 0, 1] or ids == [0, 1, 1, 1], ids
        trip = [d for d, k in zip(s, ids) if ids.count(k) == 3]
        offs = [pos[trip[1]] - pos[trip[0]], pos[trip[2]] - pos[trip[0]]]
        assert offs == [6, 14], "within-cluster session offsets are preserved"
        single = [d for d, k in zip(s, ids) if ids.count(k) == 1][0]
        assert min(abs((single - d).days) for d in trip) > gap, "clusters stay more than the gap apart"
    again = ws10.null_sets(events, valid, h, 60, [19901228, 0])
    assert all(list(a) == list(b) for a, b in zip(sets, again)), "the same seed key gives the same draws"
    other = ws10.null_sets(events, valid, h, 60, [19901228, 1])
    assert any(list(a) != list(b) for a, b in zip(sets, other)), "a different cell index gives different draws"
    assert len({tuple(s) for s in sets}) > 1


def test_null_draws_score_each_set_and_the_p_conventions(sp):
    cal, spx, events = _null_setting()
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    draws = ws10.null_draws(events, cal[251:], spx, h, 50, [19901228, 2])
    assert draws.shape == (50, 2)
    assert ((draws[:, 0] >= 0.0) & (draws[:, 0] <= 1.0)).all()
    vals = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
    assert ws10.mc_p(0.45, vals) == (1 + 1) / (1 + 5)                 # one draw at or beyond 0.45
    assert ws10.mc_p(0.3, vals) == (1 + 3) / (1 + 5)                  # "at or beyond" includes the tie
    assert ws10.mc_p(0.9, vals) == 1 / 6
    assert ws10.per_horizon_p(0.02, 0.4) == 0.4


def test_holm_known_cases(sp):
    alpha = float(ws10.get(sp, "holm.alpha"))
    for pvals, n_reject in [({"1m": 0.01, "3m": 0.03, "6m": 0.04}, 1),
                            ({"1m": 0.01, "3m": 0.02, "6m": 0.04}, 3),
                            ({"1m": 0.02, "3m": 0.03, "6m": 0.04}, 0),
                            ({"1m": 0.5, "3m": 0.016, "6m": 0.9}, 1)]:
        res = ws10.holm(pvals, alpha)
        assert sum(res["reject"].values()) == n_reject, (pvals, res)
    steps = ws10.holm({"1m": 0.01, "3m": 0.02, "6m": 0.04}, alpha)["steps"]
    assert np.allclose([s["threshold"] for s in steps], [alpha / 3, alpha / 2, alpha])


def test_power_is_one_at_a_huge_effect_and_the_size_at_zero(sp):
    cal, spx, events = _null_setting()
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    alpha = float(ws10.get(sp, "holm.alpha"))
    null = ws10.null_draws(events, cal[251:], spx, h, 300, [19901228, 3])
    big = ws10.power(events, cal[251:], spx, h, 50.0, null, 100, [19901228, 1003], alpha, 3)
    nil = ws10.power(events, cal[251:], spx, h, 0.0, null, 200, [19901228, 1003], alpha, 3)
    assert big == 1.0
    assert nil <= 0.10


# ---------------------------------------------------------------- statuses and the verdict

def test_cell_and_clause_status_rules(sp):
    assert ws10.cell_status(True, 0.1) == "PASS"
    assert ws10.cell_status(False, 0.80) == "FAIL"
    assert ws10.cell_status(False, 0.79) == "UNRESOLVED"
    assert ws10.clause_status("PASS", "PASS") == "PASS"
    assert ws10.clause_status("PASS", "FAIL") == "FAIL"
    assert ws10.clause_status("UNRESOLVED", "FAIL") == "FAIL"
    assert ws10.clause_status("PASS", "UNRESOLVED") == "UNRESOLVED"
    assert ws10.clause_status("UNRESOLVED", "UNRESOLVED") == "UNRESOLVED"


@pytest.mark.parametrize("g1, g2, g3, kwargs, expected", [
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "PASS", {}, "PROPOSE_ENGINE_CHANGE"),
    ({"S-D3": "PASS", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "PASS", {}, "PROPOSE_CONDITIONAL"),
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "DISTINCT", "S-D2": "REDUNDANT"}, "PASS", {}, "PROPOSE_CONDITIONAL"),
    ({"S-D3": "PASS", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "FAIL", {}, "ADDS_FIRES_WITHOUT_INFORMATION"),
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "REDUNDANT", "S-D2": "MISPLACED"}, "PASS", {}, "ALREADY_CARRIED"),
    ({"S-D3": "PASS", "S-D2": "FAIL"}, {"S-D3": "REDUNDANT", "S-D2": "DISTINCT"}, "FAIL", {}, "ALREADY_CARRIED"),
    ({"S-D3": "FAIL", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "FAIL", {}, "NO_INFORMATION"),
    ({"S-D3": "FAIL", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "UNRESOLVED", {}, "NO_INFORMATION"),
    ({"S-D3": "UNRESOLVED", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "FAIL", {}, "UNRESOLVED"),
    ({"S-D3": "PASS", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "UNRESOLVED", {}, "UNRESOLVED"),
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "PASS", {"thin": True}, "PROPOSE_ENGINE_CHANGE_THIN"),
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "PASS", {"stopped": True}, "STOP_STEP0"),
    ({"S-D3": "FAIL", "S-D2": "FAIL"}, {"S-D3": "NO_EVENTS", "S-D2": "DISTINCT"}, "FAIL", {}, "NO_INFORMATION"),
])
def test_verdict_mapping_is_mechanical(sp, g1, g2, g3, kwargs, expected):
    assert ws10.verdict(g1, g2, g3, **kwargs) == expected
    assert expected.replace("_THIN", "") in ws10.get(sp, "verdict.enum")
