"""Contract tests for the WS10 (thrust-subconditions) engine, committed at the freeze BEFORE the
engine exists. They define what ``scripts/ws10_subconditions.py`` and ``scripts/ws10_run.py`` must
do; the Opus build makes them pass without changing them. Every value comes from
``spec/ws10_prereg_spec.json`` (the engine reads it and never restates it) and from the planted
fixture ``tests/fixtures/ws10/expected.json`` regenerated by ``tests/make_ws10_fixture.py``, whose
reference implementation is the semantics of every function below where the words leave room.

Required API (frozen). scripts/ws10_subconditions.py:
  SPEC_PATH                                   Path of spec/ws10_prereg_spec.json
  load_spec() -> dict                         the spec
  get(spec, dotted) -> value                  raises FreezeViolation on a missing key (never a default)
  spec_hash() -> str                          sha256 hex of the spec file bytes
  FreezeViolation, BurnInRefusal, NonSessionDate, ComparatorMisuse   exception classes
  resolve_session(date, sessions) -> Timestamp               raises NonSessionDate if `date` is not in `sessions`
  candidate_share(close, member) -> Series                   per cent, 100 * count / members (multiplication first);
        a name counts only when its close and its rolling statistic are both defined (no forward fill, no padding);
        NaN where fewer than shared.share_nan_below_members members qualify; name == member
  daily_fire(share, threshold) -> Series[bool]               share >= threshold, NaN -> False
  fresh_events(share, threshold, comp) -> DatetimeIndex      first session at or above after shared.below_sessions
        consecutive DEFINED sessions strictly below; admitted on data_ok sessions at or after the first data_ok
        session; raises BurnInRefusal when comp has no data_ok session
  candidate_events(close, member, comp) -> DatetimeIndex     candidate_share then fresh_events; raises BurnInRefusal
        when len(close) < HL_LOOKBACK + the member's window_sessions (the burn-in plus its own 20 or 10)
  member_fresh_fires(boolean, comp) -> DatetimeIndex         existing_member_fresh_fire.rule on data_ok sessions
  cofire_share(cand_events, fire_dates, sessions) -> float   per cent of cand_events with a fire at most
        redundancy.window_sessions away in EITHER direction; NaN for an empty candidate set
  cofire_split(cand_events, fire_dates, sessions) -> {"before", "same", "after"}   counts of co-firing candidate
        events by whether the nearest fire is before, on, or after the candidate's session
  redundancy(cand_events, fires_by_dim, own_dimension, sessions) -> dict  keys own, d1, d4 (per cent), n_events,
        status in {DISTINCT, REDUNDANT, MISPLACED, NO_EVENTS} per redundancy.status_rule, thin (bool: n_events below
        redundancy.thin_suffix_below_events); fires_by_dim maps d1..d4 -> DatetimeIndex
  composite_with_members(panels, extra, config=None) -> DataFrame   compute_composite with extra {dim: Series[bool]}
        OR-ed into dim; equal to compute_composite(panels) on every engine column when every extra is False; an
        event is a session on which n_dimensions increases
  fresh_at(comp, threshold) -> DatetimeIndex                 event and n_dimensions >= threshold and data_ok
  before_set(comp, threshold) -> DatetimeIndex               the SEEN four-dimension set: takes no candidate argument
  added_events(before, after, threshold) -> DatetimeIndex    fresh_at(after) dates absent from fresh_at(before)
  removed_events(before, after, threshold) -> DatetimeIndex  fresh_at(before) dates absent from fresh_at(after)
  memory_window_share(added, before) -> float                per cent of `added` dates on which before.n_dimensions >= 1
  class CandidateRegistry: register(name, events); assert_comparator(events) raises ComparatorMisuse when `events`
        equals any registered candidate or added set
  forward_stats(events, index_series, horizon_sessions) -> {"n", "win_rate", "median"}  lagged one session (signal
        close T, window from the close of T+1); events whose lagged window is incomplete are dropped
  complete_window_events(events, index_series, horizon_sessions) -> DatetimeIndex   events at return-series position
        i with i + 1 + h at most the last index (horizons.complete_window_rule)
  forward_window_end(sessions, start, horizon_sessions) -> Timestamp    sessions[get_loc(start) + h]; NonSessionDate
  cluster_ids(dates, gap_days) -> list[int]; cluster_count(dates, gap_days) -> int   a gap > gap_days splits
  null_sets(events, valid_sessions, index_series, horizon_sessions, draws, seed_key) -> list[DatetimeIndex]
        the pinned SEQUENTIAL sampler (null.placement, null.restart) on the complete-window treatment events, with
        clusters.gap_calendar_days; one rng.integers(len(admissible)) call per cluster placement on
        numpy.random.default_rng(seed_key); identical to the reference ref_null_sets draw for draw
  null_draws(events, valid_sessions, index_series, horizon_sessions, draws, seed_key) -> ndarray (draws, 2)
        columns win_rate, median of each drawn set's lagged forward returns
  mc_p(observed, draw_values) -> float                       (1 + count at or beyond) / (1 + draws)
  per_horizon_p(p_win, p_med) -> float                       max
  holm(pvals, alpha) -> {"reject": {name: bool}, "steps": [{"name", "p", "threshold", "reject"}]}
  power(events, valid_sessions, index_series, horizon_sessions, delta_pp, null_values, draws, seed_key, alpha,
        family_size) -> float   share of sets drawn by the pinned sampler on seed_key whose max(p_win, p_med), after
        +delta_pp / 100 is added to every lagged return, is <= alpha / family_size against null_values
  self_drill(events, valid_sessions, index_series, horizon_sessions, null_values, drill_draws, seed_key) -> dict
        keys unconditional_win_rate, unconditional_median, null_mean_win_rate, null_mean_median, centring_pass,
        size_share_at_alpha, per self_drill in the spec (bands and alpha read from the spec)
  cell_status(cleared, power_keyed) -> "PASS" | "FAIL" | "UNRESOLVED"        power.cell_status_rule
  clause_status(early, late) -> "PASS" | "FAIL" | "UNRESOLVED"              power.clause_status_rule
  verdict(g1, g2, g3, stopped=False, thin=False) -> str     verdict.rule_in_order; g1 {cand: status}, g2 {cand: status}
scripts/ws10_run.py:
  Stop                                                      the FAIL_STOP exception
  spec_hash_or_stop(frozen) -> str                          Stop when the spec hash differs from `frozen`
  check_engine_modules(spec) -> dict                        Stop when any pinned module hash differs
  check_frozen_tree_clean(status_lines) -> None             Stop when PREREG_thrust-subconditions.md, spec/, tests/ or
        scripts/ws10_*.py appear modified, added, renamed or untracked in `git status --porcelain` lines
  event_set_guard(observed, expected) -> None               Stop when any key of `expected` differs in `observed`

Python months are 1-indexed. Date arithmetic goes through pandas only.
"""

from __future__ import annotations

import hashlib
import inspect
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

TESTS = Path(__file__).resolve().parent
ROOT = TESTS.parent
FIX = TESTS / "fixtures" / "ws10"
sys.path.insert(0, str(TESTS))
sys.path.insert(0, str(ROOT / "scripts"))

import make_ws10_fixture as ref  # noqa: E402
import compute_breadth as cb  # noqa: E402

FROZEN_SPEC_SHA256 = "b805afaf4f02988bf9d1e7b83d0f7ed4d41696a327b610371d8b78e936b13f33"

ws10 = pytest.importorskip("ws10_subconditions", reason="engine not built yet: scripts/ws10_subconditions.py missing")
runner = pytest.importorskip("ws10_run", reason="engine not built yet: scripts/ws10_run.py missing")


def _dates(xs) -> list[str]:
    return [str(pd.Timestamp(x).date()) for x in xs]


@pytest.fixture(scope="module")
def sp():
    return ws10.load_spec()


@pytest.fixture(scope="module")
def fx():
    close, volume = ref.planted()
    expected = json.loads((FIX / "expected.json").read_text(encoding="utf-8"))
    panels = cb.build_panels(close, volume)
    before = cb.compute_composite(panels)
    return close, volume, panels, before, expected


@pytest.fixture(scope="module")
def unit():
    ui = ref.unit_index()
    return ui, ref.unit_valid(ui), ref.unit_events(ui)


# ---------------------------------------------------------------- spec and hashes

def test_spec_hash_matches_frozen_value():
    assert hashlib.sha256((ROOT / "spec" / "ws10_prereg_spec.json").read_bytes()).hexdigest() == FROZEN_SPEC_SHA256
    assert ws10.spec_hash() == FROZEN_SPEC_SHA256
    assert runner.spec_hash_or_stop(FROZEN_SPEC_SHA256) == FROZEN_SPEC_SHA256
    with pytest.raises(runner.Stop):
        runner.spec_hash_or_stop("0" * 64)


def test_missing_spec_key_raises_rather_than_defaulting(sp):
    assert ws10.get(sp, "candidates.S-D3.threshold_pct") == 55.0
    assert ws10.get(sp, "candidates.S-D2.threshold_pct") == 90.0
    with pytest.raises(ws10.FreezeViolation):
        ws10.get(sp, "candidates.S-D3.threshold_pct_tuned")


def test_engine_module_hashes_are_pinned(sp):
    got = runner.check_engine_modules(sp)
    assert got == sp["engine"]["modules_sha256"]
    tampered = json.loads(json.dumps(sp))
    tampered["engine"]["modules_sha256"]["compute_breadth.py"] = "0" * 64
    with pytest.raises(runner.Stop):
        runner.check_engine_modules(tampered)


def test_dirty_frozen_tree_makes_the_runner_refuse():
    runner.check_frozen_tree_clean(["?? data_local/x.json", " M README.md", " M scripts/pipeline.py"])
    for line in (" M PREREG_thrust-subconditions.md", "?? spec/ws10_prereg_spec.json", "A  tests/test_ws10_contract.py",
                 " M tests/fixtures/ws10/expected.json", 'R  old.md -> "PREREG_thrust-subconditions.md"',
                 " M scripts/ws10_subconditions.py", "?? scripts/ws10_run.py", " M scripts/ws10_high_cache.py"):
        with pytest.raises(runner.Stop):
            runner.check_frozen_tree_clean([line])


def test_event_set_guard_stops_on_a_mismatch(sp):
    expected = sp["data"]["expected_panel"]["event_set_guard"]
    observed = {k: v for k, v in expected.items() if k not in ("source", "on_miss")}
    runner.event_set_guard(observed, expected)
    wrong = dict(observed)
    wrong["fresh_events_ge1_on_or_before_2026-09-01"] = 97
    with pytest.raises(runner.Stop):
        runner.event_set_guard(wrong, expected)
    with pytest.raises(runner.Stop):
        runner.event_set_guard({}, expected)


# ---------------------------------------------------------------- candidate shares and events on the planted panel

def test_candidate_shares_match_the_fixture(fx, sp):
    close, volume, panels, before, expected = fx
    for member in ("S-D3", "S-D2"):
        share = ws10.candidate_share(close, member)
        assert share.name == member
        assert str(share.first_valid_index().date()) == expected["first_defined"][member]
        for d, want in expected["shares"][member].items():
            got = share.loc[pd.Timestamp(d)]
            if want is None:
                assert pd.isna(got)
            elif want in (55.0, 90.0):
                assert got == want, f"{member} at {d}: expected exactly {want}, got {got!r}"
            else:
                assert abs(got - want) < 1e-9, f"{member} at {d}: {got} vs {want}"


def test_fresh_events_match_the_fixture(fx, sp):
    close, volume, panels, before, expected = fx
    for member in ("S-D3", "S-D2"):
        share = ws10.candidate_share(close, member)
        thr = ws10.get(sp, f"candidates.{member}.threshold_pct")
        assert _dates(ws10.fresh_events(share, thr, before)) == expected["fresh_events"][member]
        assert _dates(ws10.candidate_events(close, member, before)) == expected["fresh_events"][member]
        assert int(ws10.daily_fire(share, thr).sum()) == expected["daily_fire_counts"][member]


def test_share_nan_below_the_member_floor(sp):
    close, volume = ref.planted()
    thin = close.iloc[:, :300]
    assert ws10.candidate_share(thin, "S-D2").isna().all(), "fewer than 400 members with history must give NaN"


def test_a_gap_and_a_late_entrant_leave_the_denominator(fx, sp):
    close, volume, panels, before, expected = fx
    share = ws10.candidate_share(close, "S-D3")
    assert share.loc[pd.Timestamp("2020-05-06")] == 100.0 * 480 / 799      # N799's interior gap sits inside the window
    assert share.loc[pd.Timestamp("2020-03-11")] == 100.0 * 40 / 799       # N798's first close is session 300: no history yet
    cal = pd.bdate_range("2021-01-04", periods=60)
    frame = pd.DataFrame(np.full((60, 401), 100.0), index=cal, columns=[f"N{i:03d}" for i in range(401)])
    frame.iloc[30, 0] = np.nan                                            # one interior missing close in one name
    s = ws10.candidate_share(frame, "S-D3")
    assert s.iloc[19:].notna().all() and s.iloc[19:].eq(100.0).all()      # the gapped name leaves numerator and denominator
    frame.iloc[:10, 1] = np.nan                                           # a late entrant
    s2 = ws10.candidate_share(frame, "S-D3")
    assert s2.iloc[19:29].eq(100.0).all()                                 # out of the denominator until it has 20 sessions


# ---------------------------------------------------------------- refusal paths

def test_refuses_any_computation_before_the_burn_in_plus_its_own_window(sp):
    close, volume = ref.planted()
    burn = int(ws10.get(sp, "engine.constants.HL_LOOKBACK"))
    short = close.iloc[: burn + 15]                       # 267 sessions: 252 + 10 fits S-D2, 252 + 20 does not fit S-D3
    comp_short = cb.compute_composite(cb.build_panels(short, volume.iloc[: burn + 15]))
    assert comp_short["data_ok"].any()
    ws10.candidate_events(short, "S-D2", comp_short)
    with pytest.raises(ws10.BurnInRefusal):
        ws10.candidate_events(short, "S-D3", comp_short)
    tiny = close.iloc[:100]
    comp_tiny = cb.compute_composite(cb.build_panels(tiny, volume.iloc[:100]))
    assert not comp_tiny["data_ok"].any()
    for member in ("S-D3", "S-D2"):
        with pytest.raises(ws10.BurnInRefusal):
            ws10.candidate_events(tiny, member, comp_tiny)
        with pytest.raises(ws10.BurnInRefusal):
            ws10.fresh_events(ws10.candidate_share(tiny, member), 55.0, comp_tiny)


def test_no_event_inside_the_burn_in_even_when_the_share_crosses(fx, sp):
    close, volume, panels, before, expected = fx
    first_ok = pd.Timestamp(expected["first_data_ok_session"])
    for member, thr in (("S-D3", 55.0), ("S-D2", 90.0)):
        share = ws10.candidate_share(close, member)
        assert share.loc[pd.Timestamp("2019-03-27")] >= thr and pd.Timestamp("2019-03-27") < first_ok
        ev = ws10.fresh_events(share, thr, before)
        assert len(ev) and ev.min() >= first_ok


def test_non_session_date_is_refused(fx):
    close, volume, panels, before, expected = fx
    cal = close.index
    assert ws10.resolve_session(pd.Timestamp("2020-04-08"), cal) == pd.Timestamp("2020-04-08")
    for bad in ("2020-06-13", "2020-06-14", "2030-01-02"):             # a Saturday, a Sunday, beyond the panel
        with pytest.raises(ws10.NonSessionDate):
            ws10.resolve_session(pd.Timestamp(bad), cal)
        with pytest.raises(ws10.NonSessionDate):
            ws10.forward_window_end(cal, pd.Timestamp(bad), 21)


# ---------------------------------------------------------------- the member conditions pinned on tiny series

def test_flat_series_is_at_its_closing_high_under_the_inclusive_rule(sp):
    cal = pd.bdate_range("2021-01-04", periods=40)
    flat = pd.DataFrame({f"N{i:03d}": 100.0 for i in range(400)}, index=cal)
    share = ws10.candidate_share(flat, "S-D3")
    assert share.iloc[19:].eq(100.0).all(), "close >= max over the window including today holds on a flat series"
    assert share.iloc[:19].isna().all(), "no share before 20 sessions of history"
    assert ws10.candidate_share(flat, "S-D2").iloc[9:].eq(0.0).all(), "strictly above its own flat average is never true"


def test_step_then_flat_sits_above_its_ten_session_average_for_exactly_nine_sessions(sp):
    cal = pd.bdate_range("2021-01-04", periods=40)
    path = np.full(40, 100.0)
    path[20:] = 110.0                                  # one step on session 20, then exactly flat
    frame = pd.DataFrame({f"N{i:03d}": path for i in range(400)}, index=cal)
    share = ws10.candidate_share(frame, "S-D2")
    assert share.iloc[20:29].eq(100.0).all()           # sessions 20..28: above (j = 0..8)
    assert share.iloc[29] == 0.0                       # j = 9: the window is all 110, a tie is not "above"
    d3 = ws10.candidate_share(frame, "S-D3")
    assert d3.iloc[20:].eq(100.0).all()                # a step then flat stays at its 20-session high


def test_exactly_twenty_defined_sessions_below_are_required(fx, sp):
    close, volume, panels, before, expected = fx
    cal = close.index[-60:]
    comp = before.loc[cal].copy()
    assert comp["data_ok"].all()
    twenty = pd.Series([60.0] * 5 + [50.0] * 20 + [60.0] + [50.0] * 34, index=cal)
    nineteen = pd.Series([60.0] * 5 + [50.0] * 19 + [60.0] + [50.0] * 35, index=cal)
    broken = twenty.copy()
    broken.iloc[10] = np.nan
    assert _dates(ws10.fresh_events(twenty, 55.0, comp)) == [str(cal[25].date())]
    assert _dates(ws10.fresh_events(nineteen, 55.0, comp)) == []
    assert _dates(ws10.fresh_events(broken, 55.0, comp)) == []


# ---------------------------------------------------------------- redundancy

def test_member_fresh_fires_match_the_fixture(fx, sp):
    close, volume, panels, before, expected = fx
    for dim, names in sp["engine"]["members"].items():
        for m in names:
            assert _dates(ws10.member_fresh_fires(before[m], before)) == expected["member_fresh_fires"][m], m


def test_redundancy_on_the_planted_panel(fx, sp):
    close, volume, panels, before, expected = fx
    fires_by_dim = {}
    for dim, names in sp["engine"]["members"].items():
        fires_by_dim[dim] = pd.DatetimeIndex(sorted({d for m in names for d in ws10.member_fresh_fires(before[m], before)}))
    for member in ("S-D3", "S-D2"):
        cand = ws10.candidate_events(close, member, before)
        got = ws10.redundancy(cand, fires_by_dim, ws10.get(sp, f"candidates.{member}.dimension"), close.index)
        want = expected["redundancy"][member]
        for k in ("own", "d1", "d4"):
            assert abs(got[k] - want[k]) < 1e-9, (member, k, got[k], want[k])
        assert got["status"] in ("DISTINCT", "REDUNDANT", "MISPLACED")
        assert got["n_events"] == len(cand) and got["thin"] is True       # two planted events: below ten


def test_redundancy_rule_known_cases(sp):
    cal = pd.bdate_range("2020-01-02", periods=200)
    own = pd.DatetimeIndex([cal[50], cal[100], cal[150]])
    cand = pd.DatetimeIndex([cal[47], cal[53], cal[95], cal[106], cal[180]])    # leads 3, lags 3, leads 5, lags 6, far
    assert ws10.cofire_share(cand, own, cal) == 60.0, "a candidate that LEADS a member fire co-fires too"
    assert ws10.cofire_split(cand, own, cal) == {"before": 1, "same": 0, "after": 2}
    assert pd.isna(ws10.cofire_share(pd.DatetimeIndex([]), own, cal))
    none = pd.DatetimeIndex([])
    r = ws10.redundancy(cand, {"d1": none, "d2": none, "d3": own, "d4": none}, "d3", cal)
    assert r["own"] == 60.0 and r["d1"] == 0.0 and r["d4"] == 0.0 and r["status"] == "DISTINCT"
    assert r["n_events"] == 5 and r["thin"] is True
    heavy = pd.DatetimeIndex([cal[47], cal[53], cal[95], cal[106]])                 # 4 of 5 within the window
    r = ws10.redundancy(cand, {"d1": none, "d2": none, "d3": heavy, "d4": none}, "d3", cal)
    assert r["own"] == 80.0 and r["status"] == "REDUNDANT"
    r = ws10.redundancy(cand, {"d1": none, "d2": none, "d3": pd.DatetimeIndex([cal[47], cal[53], cal[95]]), "d4": own}, "d3", cal)
    assert r["own"] == 60.0 and r["d4"] == 60.0 and r["status"] == "DISTINCT", "equal shares are not MISPLACED"
    r = ws10.redundancy(cand, {"d1": none, "d2": none, "d3": pd.DatetimeIndex([cal[47]]), "d4": own}, "d3", cal)
    assert r["own"] == 20.0 and r["d4"] == 60.0 and r["status"] == "MISPLACED"
    ten = pd.DatetimeIndex([cal[i] for i in (50, 51, 52, 53, 54, 55, 56, 120, 150, 190)])
    exact70 = ws10.redundancy(ten, {"d1": none, "d2": none, "d3": pd.DatetimeIndex([cal[52]]), "d4": none}, "d3", cal)
    assert exact70["own"] == 70.0 and exact70["status"] == "DISTINCT", "exactly 70 is not above 70"
    assert exact70["n_events"] == 10 and exact70["thin"] is False
    assert ws10.redundancy(pd.DatetimeIndex([]), {"d1": none, "d2": none, "d3": own, "d4": none}, "d3", cal)["status"] == "NO_EVENTS"


# ---------------------------------------------------------------- H-M: the composite with members

def _extras(close, sp):
    extras = {}
    for member in ("S-D3", "S-D2"):
        fire = ws10.daily_fire(ws10.candidate_share(close, member), ws10.get(sp, f"candidates.{member}.threshold_pct"))
        fire.name = member
        extras[ws10.get(sp, f"candidates.{member}.dimension")] = fire
    return extras


def test_composite_with_members_is_the_engine_when_nothing_is_admitted(fx):
    close, volume, panels, before, expected = fx
    off = pd.Series(False, index=close.index, name="off")
    same = ws10.composite_with_members(panels, {"d2": off, "d3": off})
    pd.testing.assert_frame_equal(same[before.columns], before)
    assert _dates(ws10.before_set(before, 2)) == expected["h_m"]["ge2"]["before"]
    assert _dates(ws10.fresh_at(before, 3)) == expected["h_m"]["ge3"]["before"]
    for d in expected["h_m"]["ge2_events_inside_burn_in"]:
        assert pd.Timestamp(d) not in ws10.fresh_at(before, 2), "a burn-in composite event is never fresh"


def test_added_and_removed_events_match_the_fixture(fx, sp):
    close, volume, panels, before, expected = fx
    after = ws10.composite_with_members(panels, _extras(close, sp))
    for thr in (2, 3):
        want = expected["h_m"][f"ge{thr}"]
        assert _dates(ws10.fresh_at(after, thr)) == want["after"]
        assert _dates(ws10.added_events(before, after, thr)) == want["added"]
        assert _dates(ws10.removed_events(before, after, thr)) == want["removed"]
    # the OR itself: a dimension REPLACED by its candidate would leave n_dimensions untouched behind the memory
    assert {d: int(after[d].sum()) for d in ("d1", "d2", "d3", "d4")} == expected["h_m"]["after_dim_true_counts"]
    # the event rule: on the planted coincidence a memory expires as the admitted member switches on
    assert int(after["event"].sum()) == expected["h_m"]["after_event_count_all_sessions"]
    for d in expected["h_m"]["event_rule_discriminating_sessions"]:
        assert not after.loc[pd.Timestamp(d), "event"]
    assert set(after["d3_on"][after["d3_member_S-D3"]]) == {True}, "an admitted member switches its dimension on"
    added = ws10.added_events(before, after, 2)
    share = ws10.memory_window_share(added, before)
    assert 0.0 <= share <= 100.0
    assert share == 100.0 * float((before["n_dimensions"].reindex(added) >= 1).mean())


def test_the_seen_set_is_the_only_admissible_comparator(fx):
    close, volume, panels, before, expected = fx
    assert "candidate" not in " ".join(inspect.signature(ws10.before_set).parameters)
    reg = ws10.CandidateRegistry()
    cand = ws10.candidate_events(close, "S-D3", before)
    added = pd.DatetimeIndex(pd.to_datetime(expected["h_m"]["ge2"]["added"]))
    reg.register("S-D3", cand)
    reg.register("H-M.ge2.added", added)
    reg.assert_comparator(ws10.before_set(before, 2))                   # the seen four-dimension set is admissible
    for bad in (cand, added, pd.DatetimeIndex(sorted(cand))):
        with pytest.raises(ws10.ComparatorMisuse):
            reg.assert_comparator(bad)


# ---------------------------------------------------------------- forward returns, lag, windows, clusters

def test_forward_stats_are_lagged_one_session(sp):
    cal = pd.bdate_range("2019-01-02", periods=60)
    spx = pd.Series(100.0 + np.arange(60), index=cal)
    k, h = 30, int(ws10.get(sp, "horizons.sessions.1m"))
    honest = spx.iloc[k + 1 + h] / spx.iloc[k + 1] - 1.0
    leaked = spx.iloc[k + h] / spx.iloc[k] - 1.0
    got = ws10.forward_stats(pd.DatetimeIndex([cal[k]]), spx, h)
    assert got["n"] == 1 and abs(got["median"] - honest) < 1e-12 and abs(got["median"] - leaked) > 1e-9
    assert ws10.forward_stats(pd.DatetimeIndex([cal[50]]), spx, h)["n"] == 0, "an incomplete window is dropped"


def test_complete_window_rule_includes_the_lag(unit, sp):
    ui, uv, ue = unit
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    cal = ui.index
    last = len(cal) - 1
    edge = pd.DatetimeIndex([cal[last - h - 1], cal[last - h]])
    assert _dates(ws10.complete_window_events(edge, ui, h)) == [str(cal[last - h - 1].date())]
    assert ws10.forward_stats(pd.DatetimeIndex([cal[last - h]]), ui, h)["n"] == 0
    assert ws10.forward_stats(pd.DatetimeIndex([cal[last - h - 1]]), ui, h)["n"] == 1


def test_forward_window_boundaries_on_the_fixture_calendar(fx, sp):
    close, volume, panels, before, expected = fx
    h = int(ws10.get(sp, "horizons.sessions.1m"))
    for start, want in expected["boundaries_1m"].items():          # a year boundary and a month boundary
        assert str(ws10.forward_window_end(close.index, pd.Timestamp(start), h).date()) == want


def test_cluster_rule_known_cases(fx, sp):
    close, volume, panels, before, expected = fx
    gap = int(ws10.get(sp, "clusters.gap_calendar_days"))
    kc = expected["cluster_known_case"]
    assert ws10.cluster_ids(pd.to_datetime(kc["dates"]), gap) == [0, 0, 1]
    assert ws10.cluster_ids(pd.to_datetime(kc["dates_b"]), gap) == [0, 0, 0]
    assert ws10.cluster_count(pd.to_datetime(kc["dates"]), gap) == 2
    assert ws10.cluster_count(pd.DatetimeIndex([]), gap) == 0


# ---------------------------------------------------------------- the null, pinned draw for draw on the unit path

def test_null_sets_reproduce_the_pinned_draws(fx, unit, sp):
    close, volume, panels, before, expected = fx
    ui, uv, ue = unit
    nu = expected["null_unit"]
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    assert _dates(ue) == nu["events"]
    sets = ws10.null_sets(ue, uv, ui, h, 3, [19901228, 0])
    assert [_dates(s) for s in sets] == nu["first_three_draws_seed_0"], "the sequential sampler is pinned draw for draw"
    gap = int(ws10.get(sp, "clusters.gap_calendar_days"))
    pos = {d: i for i, d in enumerate(ui.index)}
    vset = set(uv)
    for s in ws10.null_sets(ue, uv, ui, h, 40, [19901228, 7]):
        assert len(s) == len(ue) and list(s) == sorted(s)
        assert all(d in vset for d in s)
        assert max(pos[d] for d in s) + 1 + h <= len(ui) - 1
        ids = ws10.cluster_ids(s, gap)
        assert len(set(ids)) == 12 and all(ids.count(k) == 2 for k in set(ids))
        for k in set(ids):
            pair = [d for d, i in zip(s, ids) if i == k]
            assert uv.get_loc(pair[1]) - uv.get_loc(pair[0]) == 7, "within-cluster offsets are preserved"
    again = ws10.null_sets(ue, uv, ui, h, 3, [19901228, 0])
    assert [_dates(s) for s in again] == nu["first_three_draws_seed_0"]
    other = ws10.null_sets(ue, uv, ui, h, 3, [19901228, 1])
    assert [_dates(s) for s in other] != nu["first_three_draws_seed_0"]


def test_null_draws_statistics_and_p_conventions(fx, unit, sp):
    close, volume, panels, before, expected = fx
    ui, uv, ue = unit
    nu = expected["null_unit"]
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    null = ws10.null_draws(ue, uv, ui, h, 300, [19901228, 0])
    assert null.shape == (300, 2)
    assert abs(null[:, 0].mean() - nu["null300_mean_win_rate"]) < 1e-12
    assert abs(null[:, 1].mean() - nu["null300_mean_median"]) < 1e-12
    treat = ws10.forward_stats(ue, ui, h)
    assert treat == nu["treatment_3m"]
    assert ws10.mc_p(treat["win_rate"], null[:, 0]) == nu["p_win_treatment"]
    assert ws10.mc_p(treat["median"], null[:, 1]) == nu["p_med_treatment"]
    vals = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
    assert ws10.mc_p(0.45, vals) == (1 + 1) / (1 + 5)                 # one draw at or beyond 0.45
    assert ws10.mc_p(0.3, vals) == (1 + 3) / (1 + 5)                  # "at or beyond" includes the tie
    assert ws10.mc_p(0.9, vals) == 1 / 6
    assert ws10.per_horizon_p(0.02, 0.4) == 0.4


def test_sampler_runs_at_thirty_clusters_and_lands_in_the_last_sessions_of_an_early_ending_window(unit, sp):
    ui, uv, ue = unit
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    many = ref.many_clusters_events(ui)
    sets = ws10.null_sets(many, uv, ui, h, 2000, [19901228, 5])
    assert len(sets) == 2000 and all(len(s) == 30 for s in sets), "thirty clusters must not exhaust the restarts"
    early = ui.index[251:1100]                                         # the return series continues to 1199
    tail = set(early[-h:])
    sets = ws10.null_sets(ue, early, ui, h, 200, [19901228, 9])
    assert any(any(d in tail for d in s) for s in sets), "the last h valid sessions are admissible: the window runs on the return series"
    assert all(all(d in set(early) for d in s) for s in sets)


def test_holm_known_cases(sp):
    alpha = float(ws10.get(sp, "holm.alpha"))
    for pvals, n_reject in [({"1m": 0.01, "3m": 0.03, "6m": 0.04}, 1),
                            ({"1m": 0.01, "3m": 0.02, "6m": 0.04}, 3),
                            ({"1m": 0.02, "3m": 0.03, "6m": 0.04}, 0),
                            ({"1m": 0.5, "3m": 0.016, "6m": 0.9}, 1)]:
        res = ws10.holm(pvals, alpha)
        assert sum(res["reject"].values()) == n_reject, (pvals, res)
    steps = ws10.holm({"1m": 0.01, "3m": 0.02, "6m": 0.04}, alpha)["steps"]
    assert [s["threshold"] for s in steps] == [alpha / 3, alpha / 2, alpha / 1]


def test_power_reproduces_the_pinned_values(fx, unit, sp):
    close, volume, panels, before, expected = fx
    ui, uv, ue = unit
    nu = expected["null_unit"]
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    alpha = float(ws10.get(sp, "holm.alpha"))
    null = ws10.null_draws(ue, uv, ui, h, 300, [19901228, 0])
    for delta, want in nu["power_by_delta_pp"].items():
        got = ws10.power(ue, uv, ui, h, float(delta), null, 100, [19901228, 1000], alpha, 3)
        assert got == want, (delta, got, want)
    assert nu["power_by_delta_pp"]["50.0"] == 1.0 and 0.05 < nu["power_by_delta_pp"]["10.0"] < 0.95


def test_self_drill_reproduces_the_pinned_values_and_rejects_a_shifted_null(fx, unit, sp):
    close, volume, panels, before, expected = fx
    ui, uv, ue = unit
    nu = expected["null_unit"]
    h = int(ws10.get(sp, "horizons.sessions.3m"))
    null = ws10.null_draws(ue, uv, ui, h, 300, [19901228, 0])
    got = ws10.self_drill(ue, uv, ui, h, null, 100, [19901228, 2000])
    want = nu["self_drill"]
    assert got["centring_pass"] is True and got["size_share_at_alpha"] == want["size_share_at_alpha"]
    for k in ("unconditional_win_rate", "unconditional_median", "null_mean_win_rate", "null_mean_median"):
        assert abs(got[k] - want[k]) < 1e-12, k
    shifted = null.copy()
    shifted[:, 0] += 0.2
    assert ws10.self_drill(ue, uv, ui, h, shifted, 100, [19901228, 2000])["centring_pass"] is False


# ---------------------------------------------------------------- statuses and the verdict

def test_cell_and_clause_status_rules(sp):
    assert ws10.cell_status(True, 0.1) == "PASS"
    assert ws10.cell_status(False, 0.80) == "FAIL"
    assert ws10.cell_status(False, 0.79) == "UNRESOLVED"
    assert ws10.cell_status(False, 0.0) == "UNRESOLVED", "a cell with no treatment event has power 0"
    assert ws10.clause_status("PASS", "PASS") == "PASS"
    assert ws10.clause_status("PASS", "FAIL") == "FAIL"
    assert ws10.clause_status("UNRESOLVED", "FAIL") == "FAIL"
    assert ws10.clause_status("PASS", "UNRESOLVED") == "UNRESOLVED"
    assert ws10.clause_status("UNRESOLVED", "UNRESOLVED") == "UNRESOLVED"


@pytest.mark.parametrize("g1, g2, g3, kwargs, expected", [
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "PASS", {}, "PROPOSE_ENGINE_CHANGE"),
    ({"S-D3": "PASS", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "PASS", {}, "PROPOSE_CONDITIONAL"),
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "DISTINCT", "S-D2": "REDUNDANT"}, "PASS", {}, "PROPOSE_CONDITIONAL"),
    ({"S-D3": "PASS", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "FAIL", {}, "ADDS_FIRES_WITHOUT_INFORMATION"),
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "REDUNDANT", "S-D2": "MISPLACED"}, "PASS", {}, "ALREADY_CARRIED"),
    ({"S-D3": "PASS", "S-D2": "FAIL"}, {"S-D3": "REDUNDANT", "S-D2": "DISTINCT"}, "FAIL", {}, "ALREADY_CARRIED"),
    ({"S-D3": "FAIL", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "FAIL", {}, "NO_INFORMATION"),
    ({"S-D3": "FAIL", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "UNRESOLVED", {}, "NO_INFORMATION"),
    ({"S-D3": "UNRESOLVED", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "FAIL", {}, "UNRESOLVED"),
    ({"S-D3": "PASS", "S-D2": "FAIL"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "UNRESOLVED", {}, "UNRESOLVED"),
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "PASS", {"thin": True}, "PROPOSE_ENGINE_CHANGE_THIN"),
    ({"S-D3": "PASS", "S-D2": "PASS"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "PASS", {"stopped": True}, "STOP_STEP0"),
    ({"S-D3": "UNRESOLVED", "S-D2": "UNRESOLVED"}, {"S-D3": "NO_EVENTS", "S-D2": "DISTINCT"}, "UNRESOLVED", {}, "UNRESOLVED"),
    ({"S-D3": "UNRESOLVED", "S-D2": "UNRESOLVED"}, {"S-D3": "DISTINCT", "S-D2": "DISTINCT"}, "UNRESOLVED", {"thin": True}, "UNRESOLVED_THIN"),
])
def test_verdict_mapping_is_mechanical(sp, g1, g2, g3, kwargs, expected):
    assert ws10.verdict(g1, g2, g3, **kwargs) == expected
    assert expected.replace("_THIN", "") in ws10.get(sp, "verdict.enum")
